### ISSUE TITLE
Add Blue Wallet API (LNDHub) client?

### ISSUE THREAD

**Issue by kristapsk** [SatSale/SatSale#101]
https://github.com/snow884/blue_wallet_client

Currently SatSale users can accept onchain Bitcoin payments without running full node, but it is not possible for LN payments. This Blue Wallet API (LNDHub) client could be a custodial non-KYC alternative for small merchants to accept LN without running node. Also especially makes sense with weak hands mode enabled, where funds stay at custodial wallet only for short amount of time (although we could probably even have SideShift as node backend there and ask for LN invoices directly from them too).

**Comment by nickfarrow** [comment]
This was one of my original visions for SatSale and it would be awesome to achieve this. Previously I was looking at blockstream greenlight but blue wallet API is likely easier
