### ISSUE TITLE
Using a non default config path

### ISSUE THREAD

**Issue by lirre8** [SatSale/SatSale#138]
In config.py, it looks like it should be possible to specify a non default config file path by using cli arg `--conf`:
https://github.com/SatSale/SatSale/blob/f7ff56332f504fd7fe6195ebb671fccb8c71aa8f/config.py#L5-L9

But when running with `gunicorn -w 1 -b 0.0.0.0:8000 satsale:app --conf /path/to/config.toml`, this argument is used by gunicorn which throws an error about an invalid config file.

Maybe I'm not using it correct? How is the `--conf` arg suppose to be used?

**Comment by nickfarrow** [comment]
Hey!

Does adding two hyphens `--` escape the gunicorn arguments? Like
```
gunicorn -w 1 -b 0.0.0.0:8000 satsale:app -- --conf config2.toml
``` 
Let me know if that works, I think that is what ive been doing in rust. I might have to update some docs somewhere?

**Comment by lirre8** [comment]
It's working, thanks! I don't think it's documented anywhere, I just found that piece of code in config.py. Might be nice to include in the run section: https://github.com/SatSale/SatSale#run-satsale
