### ISSUE TITLE
[improvement] xpub mode should check if address was already used

### ISSUE THREAD

**Issue by renemadeira** [SatSale/SatSale#144]
Hello,
I know that is discouraged to use the xpub mode in production, but I believe that my use case is safer this way, and a lot of people may have the same specs.
I have a headless server with bitcoin core running, and don't want to have a wallet in my node, since it is not straightforward to manage a wallet from bitcoin-cli, and also is complicated to have a watch only wallet.
What I do is to have a zpub in satsale, and point the block explorer api to my own instance of mempool. That way I wont expose my addresses, and can have a wallet just for receiving from SatSale, and use a more friendly wallet to manage the funds.
However, I noticed that SatSale would generate the addresses following a sequence, and it seems not to check if the address was used before.
Is it something that could be implemented?
Thank you for the amazing piece of software.

**Comment by kristapsk** [comment]
Code do check address reuse, there is while loop until there are no coins in address.

https://github.com/SatSale/SatSale/blob/752215f7e29830538f30c2873a1d53ce320b6430/node/xpub.py#L148-L150

**Comment by renemadeira** [comment]
Ok, but if there is no coin in the address, but is was used? I'll try to figure out something and make a PR

> Code do check address reuse, there is while loop until there are no coins in address.
> 
> https://github.com/SatSale/SatSale/blob/752215f7e29830538f30c2873a1d53ce320b6430/node/xpub.py#L148-L150

**Comment by kristapsk** [comment]
> Ok, but if there is no coin in the address, but is was used?

It will still work. SatSale in xpub node calls [mempool.space GET Address](https://mempool.space/docs/api/rest#get-address) and then checks `funded_txo_sum` which is not decreased when UTXO is spent, instead amount gets added to `spent_txo_sum`, which SatSale doesn't check.

**Comment by renemadeira** [comment]
Okay, sorry it took me long to answer.
I tested again and it seems to work as intended.
I don't know why it went wrong the fist time, maybe a mempool communication problem, as I'm using my own instance of mempool.
Thanks for clarifying.
