### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by afeezaziz** [SatSale/SatSale#156]
Website demo is not working. Please see screenshot for evidence. If you need help, please let me know.

<img width="1079" alt="Screenshot 2023-09-11 at 2 27 39 PM" src="https://github.com/SatSale/SatSale/assets/677026/5911e220-7aa8-427e-9f51-9fc4d7ec0b04">
<img width="1470" alt="Screenshot 2023-09-11 at 2 27 33 PM" src="https://github.com/SatSale/SatSale/assets/677026/bd1d415b-4d02-4d03-9263-b1a238d1c001">

**Comment by kristapsk** [comment]
It's known issue, reason is that upgrade to Python 3.11 broke SatSale. https://twitter.com/SatoshiSale/status/1700174687240647107

There are attempts to fix this, see #150 and #155.
