### ISSUE TITLE
Replace USD with sats in donation field

### ISSUE THREAD

**Issue by nickfarrow** [SatSale/SatSale#18]
Would be cool to have a config option like `sats_donation_field = True` that replaces the USD field with satoshis on `donation.html`.

This config option would trigger some function in `satsale.py` that changes:
1) "USD" to "sats" in `donate.html
2) Updated payment logic to receive the sats amount rather than USD. Probably easiest to then convert sats to USD and use that for the rest of the payment logic.

**Comment by nickfarrow** [comment]
Should probably be implemented after this feature
https://github.com/nickfarrow/SatSale/issues/16

**Comment by kristapsk** [comment]
How about having multiple configurable currency options, with BTC / sats being one of them? Could be dropdown selection in donation.html next to amount input field.

**Comment by eddiepease** [comment]
Happy to take this one on!

**Comment by kristapsk** [comment]
@eddiepease You are working on this or still plan to do so? If not, I could do this.

**Comment by eddiepease** [comment]
I've written the code which is [here](https://github.com/SatSale/SatSale/compare/master...eddiepease:multiple_currencies) but haven't been able to properly test it yet as having lots of issues connecting to my node - still working on it but if you were able to quickly test it / tweak it if necessary that would be very helpful as don't want to hold things up...

**Comment by kristapsk** [comment]
@eddiepease I think you can open a pull request, I will help with review and testing. But I noticed some unrelated changes with imports in unrelated files with this diff.

**Comment by eddiepease** [comment]
Thanks @kristapsk! [PR raised](https://github.com/SatSale/SatSale/pull/72) with explanatory comments
