### ISSUE TITLE
xpub only mode

### ISSUE THREAD

**Issue by nickfarrow** [SatSale/SatSale#19]
It would be extremely powerful to have:
- An option in `config.py` like `pay_method = "xpub"` and `xpub=....`.
- a payment method `pay/xpub.py` that generates bitcoin addresses, and stores the current index to a file to prevent address reuse.
- It is very important that this is done in a safe way, ideally using some established python library to generate addresses from the xpub/zpub in a random way with correct derivation paths.

If you know a good library, it should be pretty simple!

**Comment by hodl** [comment]
https://github.com/mcdallas/cryptotools is a good library that I have used before to work with X/Y/Z pubs

**Comment by kristapsk** [comment]
Agree, this would be very useful. I could accept donations directly to JoinMarket yield generator wallet with tthis, for example.

In JoinMarket we currently use [python-bitcointx](https://github.com/Simplexum/python-bitcointx), which has code for BIP32 HD key derivation.

**Comment by nickfarrow** [comment]
Working attempt in https://github.com/nickfarrow/SatSale/pull/36

**Comment by nickfarrow** [comment]
yep merged 6b92367cb4ee6c5a28ef27b825c46c3b61d8fa2f
